# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  Exclude:
    - 'config/initializers/devise.rb'
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'